export const GET_ALL_CATEGORIES = "GET_ALL_CATEGORIES";
export type GET_ALL_CATEGORIES = typeof GET_ALL_CATEGORIES;

export const ADD_NEW_CATEGORY = "ADD_NEW_CATEGORY";
export type ADD_NEW_CATEGORY = typeof ADD_NEW_CATEGORY;