export const enum CommentActionTypes {
    GET_COMMENTS_BY_POST_ID = "@@comment/GET_COMMENTS_BY_POST_ID",
    ADD_NEW_COMMENT = "@@comment/ADD_NEW_COMMENT",
    VIEW_COMMENT_DETAILS_BY_ID = "@@comment/VIEW_COMMENT_DETAILS_BY_ID",
    VOTE_COMMENT_BY_ID = "@@comment/VOTE_COMMENT_BY_ID",
    EDIT_COMMENT_DETAILS_BY_ID = "@@comment/EDIT_COMMENT_DETAILS_BY_ID",
    DELETE_COMMENT_BY_ID = "@@comment/DELETE_COMMENT_BY_ID"
}