export const enum PostActionTypes {
    GET_POSTS_BY_CATEGORY = "@@post/GET_POSTS_BY_CATEGORY",
    GET_ALL_POSTS = "@@post/GET_ALL_POSTS",
    ADD_NEW_POST = "@@post/ADD_NEW_POST",
    VIEW_POST_DETAILS_BY_ID = "@@post/VIEW_POST_DETAILS_BY_ID",
    VOTE_POST_BY_ID = "V@@post/OTE_POST_BY_ID",
    EDIT_POST_DETAILS_BY_ID = "@@post/EDIT_POST_DETAILS_BY_ID",
    DELETE_POST_BY_ID = "@@post/DELETE_POST_BY_ID"
}